use_frameworks!
platform :ios, "13.0"

target 'BitLabs_Example' do
  pod 'BitLabs', :path => '../'

  target 'BitLabs_Tests' do
    inherit! :search_paths

  #  pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
