use_frameworks!
platform :ios, "12.0"

target 'BitLabs_Example' do
  
  pod 'BitLabs', :path => '../'
  pod 'BitLabs/UnitTests', :path => '../' # removed due to compatibility issue with OHHTTPStubs
  #  pod 'BitLabs/UITests', :path => '../' # removed due to errors regarding the Host
  
end
