use_frameworks!
platform :ios, "12.0"

target 'BitLabs_Example' do
  
  pod 'BitLabs', :path => '../'
  #  pod 'BitLabs/UITests', :path => '../' # removed due to errors regarding the Host
  
  target 'UnitTests' do
    inherit! :search_paths
    pod 'Mocker'
  end
  
end
