name: Pod

on:
  push:
  pull_request:
  
  
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          (cd Example && pod install)
          
      - name: Run tests
        run: xcodebuild test -workspace Example/BitLabs.xcworkspace -scheme BitLabs_Example -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
        
      - name: Lint Podspec
        run: pod lib lint
