name: Publish to CocoaPods

on:
  release:
    types: [ publish ]
  
  
jobs:
  publish:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          (cd Example && pod install)
        
      - name: Run Spec Lint
        run: pod spec lint
        
      - name: Run Publish
        run: pod trunk push
