name: Publish to CocoaPods

on:
  release:
    types: [ published ]
  
  
jobs:
  publish:
    runs-on: macos-13
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          (cd Example && pod install)
        
      - name: Publish BitLabs
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push BitLabs.podspec
        
      - name: Publish BLCustom
        env:
          COCOAPODS_TRUNK_TOKEN: ${{secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push BLCustom.podspec
