name: Testing and Linting

on:
  push:
  
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          (cd Example && pod install)
        
      - name: Create Keys.plist
        run: |
            cat <<EOF > Example/Example_BitLabs/Keys.plist
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
                <dict>
                    <key>APP_TOKEN</key>
                    <string>test</string>
                </dict>
            </plist>
        
      - name: Run tests
        run: xcodebuild test -workspace Example/BitLabs.xcworkspace -scheme BitLabs_Example -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
        
      - name: Lint Podspec
        run: pod lib lint --allow-warnings
